View IDs generated by LauncherModel.getCellLayoutChildId() method are not unique enough, which occasionally causes following exception:
java.lang.IllegalArgumentException: Wrong state class, expecting View State
but received class android.appwidget.AppWidgetHostView$ParcelableSparseArray
instead. This usually happens when two views of different type have the same
id in the same hierarchy. This view's id is NO_ID. Make sure other views do
not use the same id.

Replacing with View.generateId() available starting API 17.